[package]
name = "cachyos-hello"
version = "0.9.6"
authors = ["Vladislav Nepogodin <nepogodin.vlad@gmail.com>"]
license = "GPLv3"
edition = "2021"

[dependencies]
alpm = { default-features = false, version = "2.2.1" }
alpm-utils = { features = ["conf"], default-features = false, version = "2.0.0" }
pacmanconf = "2.0.0"

subprocess = "0.2.9"
once_cell = { default-features = false, version = "1.17.1" }
gettext-rs = { version = "0.7", default-features = false }
gtk = { version = "0.17.0", default-features = false }
gio = { version = "0.17.3", default-features = false }
gdk = "0.17.0"
gdk-pixbuf = "0.17.0"
glib = { default-features = false, version = "0.17.3" }
serde = { version = "1.0.155", default-features = false }
serde_json = "1.0.94"
reqwest = { version = "0.11.14", features = ["blocking"] }

[profile.release]
strip = "symbols"
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
